version: '3.6'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.4.2.11
    restart: always
    ports:
      - "19005:9005"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
    volumes:
      - ./entrypoint-initdb.d-clickhouse:/docker-entrypoint-initdb.d
  postgres:
    build: .
    restart: always
    depends_on:
      - "clickhouse"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - ./entrypoint-initdb.d-postgres:/docker-entrypoint-initdb.d
  graphql-engine:
    image: hasura/graphql-engine:v2.15.2
    network_mode: "host"
    # ports:
    #   - "8080:8080"
    # depends_on:
    #   - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hasura:password@localhost:5432/hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
